# Generated by Django 3.1 on 2020-09-18 05:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_head', models.CharField(max_length=100)),
                ('blo_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('blog_admin', models.CharField(default='', max_length=50)),
                ('blog_date', models.DateField()),
                ('blog_image', models.ImageField(default='', upload_to='images')),
                ('blog_teacher', models.CharField(max_length=50)),
                ('blog_teacher_content', models.CharField(max_length=200)),
                ('blog_teacher_image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
