# Generated by Django 3.1 on 2020-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200918_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_teacher_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
