# Generated by Django 3.1 on 2020-09-18 13:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200918_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('category_image', models.ImageField(default='', upload_to='shop/images')),
                ('old_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('desc', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
