# Generated by Django 3.1 on 2020-09-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('testimonial_name', models.CharField(max_length=50)),
                ('testimonial_content', models.CharField(default='', max_length=500)),
                ('testimonial_post', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='shop.category'),
        ),
    ]
